In [1]:
import polars as pl
import ast

pl.Config.set_fmt_str_lengths(100)

polars.config.Config

In [6]:
file_path = "../data/s01_raw/recipenlg.csv"

df_raw = pl.read_csv(file_path, n_rows=1000)

print(f"Shape: {df_raw.shape}")
df_raw.head()

Shape: (1000, 7)

shape: (5, 7)
┌─────┬────────────────┬────────────────┬───────────────┬───────────────┬──────────┬───────────────┐
│     ┆ title          ┆ ingredients    ┆ directions    ┆ link          ┆ source   ┆ NER           │
│ --- ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---      ┆ ---           │
│ i64 ┆ str            ┆ str            ┆ str           ┆ str           ┆ str      ┆ str           │
╞═════╪════════════════╪════════════════╪═══════════════╪═══════════════╪══════════╪═══════════════╡
│ 0   ┆ No-Bake Nut    ┆ ["1 c. firmly  ┆ ["In a heavy  ┆ www.cookbooks ┆ Gathered ┆ ["brown       │
│     ┆ Cookies        ┆ packed brown   ┆ 2-quart       ┆ .com/Recipe-D ┆          ┆ sugar",       │
│     ┆                ┆ sugar", "1/2   ┆ saucepan, mix ┆ etails.aspx?i ┆          ┆ "milk",       │
│     ┆                ┆ c. evaporated  ┆ brown sugar,  ┆ d=44874       ┆          ┆ "vanilla",    │
│     ┆                ┆ milk", "1/2    ┆ nuts,         ┆               ┆          ┆ "nuts",       │
│     ┆                ┆ tsp. vanilla", ┆ evaporated    ┆               ┆          ┆ "butter",     │
│     ┆                ┆ "1/2 c. broken ┆ milk and      ┆               ┆          ┆ "bite size    │
│     ┆                ┆ nuts…          ┆ butter or     ┆               ┆          ┆ shredded rice │
│     ┆                ┆                ┆ margarine.",  ┆               ┆          ┆ biscuits"]    │
│     ┆                ┆                ┆ "St…          ┆               ┆          ┆               │
│ 1   ┆ Jewell Ball'S  ┆ ["1 small jar  ┆ ["Place       ┆ www.cookbooks ┆ Gathered ┆ ["beef",      │
│     ┆ Chicken        ┆ chipped beef,  ┆ chipped beef  ┆ .com/Recipe-D ┆          ┆ "chicken      │
│     ┆                ┆ cut up", "4    ┆ on bottom of  ┆ etails.aspx?i ┆          ┆ breasts",     │
│     ┆                ┆ boned chicken  ┆ baking        ┆ d=699419      ┆          ┆ "cream of     │
│     ┆                ┆ breasts", "1   ┆ dish.",       ┆               ┆          ┆ mushroom      │
│     ┆                ┆ can cream of   ┆ "Place        ┆               ┆          ┆ soup", "sour  │
│     ┆                ┆ mushroom       ┆ chicken on    ┆               ┆          ┆ cream"]       │
│     ┆                ┆ soup", "1 c…   ┆ top of        ┆               ┆          ┆               │
│     ┆                ┆                ┆ beef.", "Mix  ┆               ┆          ┆               │
│     ┆                ┆                ┆ soup and      ┆               ┆          ┆               │
│     ┆                ┆                ┆ crea…         ┆               ┆          ┆               │
│ 2   ┆ Creamy Corn    ┆ ["2 (16 oz.)   ┆ ["In a slow   ┆ www.cookbooks ┆ Gathered ┆ ["frozen      │
│     ┆                ┆ pkg. frozen    ┆ cooker,       ┆ .com/Recipe-D ┆          ┆ corn", "cream │
│     ┆                ┆ corn", "1 (8   ┆ combine all   ┆ etails.aspx?i ┆          ┆ cheese",      │
│     ┆                ┆ oz.) pkg.      ┆ ingredients.  ┆ d=10570       ┆          ┆ "butter",     │
│     ┆                ┆ cream cheese,  ┆ Cover and     ┆               ┆          ┆ "garlic       │
│     ┆                ┆ cubed", "1/3   ┆ cook on low   ┆               ┆          ┆ powder",      │
│     ┆                ┆ c. butter,     ┆ for 4 hours   ┆               ┆          ┆ "salt",       │
│     ┆                ┆ cubed", "1/2   ┆ or until      ┆               ┆          ┆ "pepper"]     │
│     ┆                ┆ t…             ┆ heated throu… ┆               ┆          ┆               │
│ 3   ┆ Chicken Funny  ┆ ["1 large      ┆ ["Boil and    ┆ www.cookbooks ┆ Gathered ┆ ["chicken",   │
│     ┆                ┆ whole          ┆ debone        ┆ .com/Recipe-D ┆          ┆ "chicken      │
│     ┆                ┆ chicken", "2   ┆ chicken.",    ┆ etails.aspx?i ┆          ┆ gravy",       │
│     ┆                ┆ (10 1/2 oz.)   ┆ "Put bite     ┆ d=897570      ┆          ┆ "cream of     │
│     ┆                ┆ cans chicken   ┆ size pieces   ┆               ┆          ┆ mushroom      │
│     ┆                ┆ gravy", "1 (10 ┆ in average    ┆               ┆          ┆ soup",        │
│     ┆                ┆ 1/2 oz.) can   ┆ size square   ┆               ┆          ┆ "shredded     │
│     ┆                ┆ cream of       ┆ casserole     ┆               ┆          ┆ cheese"]      │
│     ┆                ┆ mushroom…      ┆ dish.", "Pour ┆               ┆          ┆               │
│     ┆                ┆                ┆ gr…           ┆               ┆          ┆               │
│ 4   ┆ Reeses         ┆ ["1 c. peanut  ┆ ["Combine     ┆ www.cookbooks ┆ Gathered ┆ ["peanut      │
│     ┆ Cups(Candy)    ┆ butter", "3/4  ┆ first four    ┆ .com/Recipe-D ┆          ┆ butter",      │
│     ┆                ┆ c. graham      ┆ ingredients   ┆ etails.aspx?i ┆          ┆ "graham       │
│     ┆                ┆ cracker        ┆ and press in  ┆ d=659239      ┆          ┆ cracker       │
│     ┆                ┆ crumbs", "1 c. ┆ 13 x 9-inch   ┆               ┆          ┆ crumbs",      │
│     ┆                ┆ melted         ┆ ungreased     ┆               ┆          ┆ "butter",     │
│     ┆                ┆ butter", "1    ┆ pan.", "Melt  ┆               ┆          ┆ "powdered     │
│     ┆                ┆ lb. (3 1/2 c.) ┆ chocolate     ┆               ┆          ┆ sugar",       │
│     ┆                ┆ powde…         ┆ chips and…    ┆               ┆          ┆ "chocolate    │
│     ┆                ┆                ┆               ┆               ┆          ┆ chips"]       │
└─────┴────────────────┴────────────────┴───────────────┴───────────────┴──────────┴───────────────┘

In [8]:
df_raw.select(["title", "ingredients", "NER"]).head(10)

shape: (10, 3)
┌──────────────────────────┬───────────────────────────────────┬───────────────────────────────────┐
│ title                    ┆ ingredients                       ┆ NER                               │
│ ---                      ┆ ---                               ┆ ---                               │
│ str                      ┆ str                               ┆ str                               │
╞══════════════════════════╪═══════════════════════════════════╪═══════════════════════════════════╡
│ No-Bake Nut Cookies      ┆ ["1 c. firmly packed brown        ┆ ["brown sugar", "milk",           │
│                          ┆ sugar", "1/2 c. evaporated milk", ┆ "vanilla", "nuts", "butter",      │
│                          ┆ "1/2 tsp. vanilla", "1/2 c.       ┆ "bite size shredded rice          │
│                          ┆ broken nuts…                      ┆ biscuits"]                        │
│ Jewell Ball'S Chicken    ┆ ["1 small jar chipped beef, cut   ┆ ["beef", "chicken breasts",       │
│                          ┆ up", "4 boned chicken breasts",   ┆ "cream of mushroom soup", "sour   │
│                          ┆ "1 can cream of mushroom soup",   ┆ cream"]                           │
│                          ┆ "1 c…                             ┆                                   │
│ Creamy Corn              ┆ ["2 (16 oz.) pkg. frozen corn",   ┆ ["frozen corn", "cream cheese",   │
│                          ┆ "1 (8 oz.) pkg. cream cheese,     ┆ "butter", "garlic powder",        │
│                          ┆ cubed", "1/3 c. butter, cubed",   ┆ "salt", "pepper"]                 │
│                          ┆ "1/2 t…                           ┆                                   │
│ Chicken Funny            ┆ ["1 large whole chicken", "2 (10  ┆ ["chicken", "chicken gravy",      │
│                          ┆ 1/2 oz.) cans chicken gravy", "1  ┆ "cream of mushroom soup",         │
│                          ┆ (10 1/2 oz.) can cream of         ┆ "shredded cheese"]                │
│                          ┆ mushroom…                         ┆                                   │
│ Reeses Cups(Candy)       ┆ ["1 c. peanut butter", "3/4 c.    ┆ ["peanut butter", "graham cracker │
│                          ┆ graham cracker crumbs", "1 c.     ┆ crumbs", "butter", "powdered      │
│                          ┆ melted butter", "1 lb. (3 1/2 c.) ┆ sugar", "chocolate chips"]        │
│                          ┆ powde…                            ┆                                   │
│ Cheeseburger Potato Soup ┆ ["6 baking potatoes", "1 lb. of   ┆ ["baking potatoes", "extra lean   │
│                          ┆ extra lean ground beef", "2/3 c.  ┆ ground beef", "butter", "milk",   │
│                          ┆ butter or margarine", "6 c.       ┆ "salt", "pepper", "Cheddar        │
│                          ┆ milk", …                          ┆ cheese", …                        │
│ Rhubarb Coffee Cake      ┆ ["1 1/2 c. sugar", "1/2 c.        ┆ ["sugar", "butter", "egg",        │
│                          ┆ butter", "1 egg", "1 c.           ┆ "buttermilk", "flour", "salt",    │
│                          ┆ buttermilk", "2 c. flour", "1/2   ┆ "soda", "buttermilk", "rhubarb",  │
│                          ┆ tsp. salt", "1 ts…                ┆ "vanilla"…                        │
│ Scalloped Corn           ┆ ["1 can cream-style corn", "1 can ┆ ["cream-style corn", "whole       │
│                          ┆ whole kernel corn", "1/2 pkg.     ┆ kernel corn", "crackers", "egg",  │
│                          ┆ (approximately 20) saltine        ┆ "butter", "pepper"]               │
│                          ┆ crackers,…                        ┆                                   │
│ Nolan'S Pepper Steak     ┆ ["1 1/2 lb. round steak (1-inch   ┆ ["tomatoes", "water", "onions",   │
│                          ┆ thick), cut into strips", "1 can  ┆ "Worcestershire sauce", "green    │
│                          ┆ drained tomatoes, cut up (save    ┆ peppers", "oil"]                  │
│                          ┆ liqu…                             ┆                                   │
│ Millionaire Pie          ┆ ["1 large container Cool Whip",   ┆ ["pineapple", "condensed milk",   │
│                          ┆ "1 large can crushed pineapple",  ┆ "lemons", "pecans", "graham       │
│                          ┆ "1 can condensed milk", "3        ┆ cracker crusts"]                  │
│                          ┆ lemons",…                         ┆                                   │
└──────────────────────────┴───────────────────────────────────┴───────────────────────────────────┘

In [9]:
def parse_str_list(s):
    """
    Parse a stringified list, return a list if successful, else return empty list.
    """
    try:
        result = ast.literal_eval(s)
        if isinstance(result, list):
            return result
        else:
            return []
    except Exception:
        return []
      
df_clean = (
  df_raw
  # 1. Safely parse the stringified lists into actual Python lists
  .with_columns([
    pl.col("ingredients").map_elements(parse_str_list, return_dtype=pl.List(pl.Utf8)).alias("raw_ingredients"),
    pl.col("NER").map_elements(parse_str_list, return_dtype=pl.List(pl.Utf8)).alias("ner_ingredients")
  ])
  # 2. Add unified schema columns
  .with_columns([
    pl.lit("recipenlg").alias("source_dataset"),
    pl.lit("en").alias("language"),
    (pl.lit("recipenlg_") + pl.arange(0, df_raw.height).cast(pl.Utf8)).alias("recipe_id")
  ])
  # 3. Select only the columns used in the final schema
  .select([
    "recipe_id",
    "source_dataset",
    "language",
    "raw_ingredients",
    "ner_ingredients", 
  ])
)

df_clean.head()

shape: (5, 5)
┌─────────────┬────────────────┬──────────┬────────────────────────────┬───────────────────────────┐
│ recipe_id   ┆ source_dataset ┆ language ┆ raw_ingredients            ┆ ner_ingredients           │
│ ---         ┆ ---            ┆ ---      ┆ ---                        ┆ ---                       │
│ str         ┆ str            ┆ str      ┆ list[str]                  ┆ list[str]                 │
╞═════════════╪════════════════╪══════════╪════════════════════════════╪═══════════════════════════╡
│ recipenlg_0 ┆ recipenlg      ┆ en       ┆ ["1 c. firmly packed brown ┆ ["brown sugar", "milk", … │
│             ┆                ┆          ┆ sugar", "1/2 c. evaporated ┆ "bite size shredded rice  │
│             ┆                ┆          ┆ milk", … "3 1/2 c. bite    ┆ biscuits"]                │
│             ┆                ┆          ┆ size shredded rice bis…    ┆                           │
│ recipenlg_1 ┆ recipenlg      ┆ en       ┆ ["1 small jar chipped      ┆ ["beef", "chicken         │
│             ┆                ┆          ┆ beef, cut up", "4 boned    ┆ breasts", … "sour cream"] │
│             ┆                ┆          ┆ chicken breasts", … "1     ┆                           │
│             ┆                ┆          ┆ carton sour cream"]        ┆                           │
│ recipenlg_2 ┆ recipenlg      ┆ en       ┆ ["2 (16 oz.) pkg. frozen   ┆ ["frozen corn", "cream    │
│             ┆                ┆          ┆ corn", "1 (8 oz.) pkg.     ┆ cheese", … "pepper"]      │
│             ┆                ┆          ┆ cream cheese, cubed", …    ┆                           │
│             ┆                ┆          ┆ "1/4 tsp. pepper"]         ┆                           │
│ recipenlg_3 ┆ recipenlg      ┆ en       ┆ ["1 large whole chicken",  ┆ ["chicken", "chicken      │
│             ┆                ┆          ┆ "2 (10 1/2 oz.) cans       ┆ gravy", … "shredded       │
│             ┆                ┆          ┆ chicken gravy", … "4 oz.   ┆ cheese"]                  │
│             ┆                ┆          ┆ shredded cheese"]          ┆                           │
│ recipenlg_4 ┆ recipenlg      ┆ en       ┆ ["1 c. peanut butter",     ┆ ["peanut butter", "graham │
│             ┆                ┆          ┆ "3/4 c. graham cracker     ┆ cracker crumbs", …        │
│             ┆                ┆          ┆ crumbs", … "1 large pkg.   ┆ "chocolate chips"]        │
│             ┆                ┆          ┆ chocolate chips"]          ┆                           │
└─────────────┴────────────────┴──────────┴────────────────────────────┴───────────────────────────┘

In [11]:
df_exploded = df_clean.select(["recipe_id", "ner_ingredients"]).explode("ner_ingredients")

print(f"Total unique ner ingredients strings in this 1000-recipe chunk: {df_exploded['ner_ingredients'].n_unique()}")
df_exploded.head(10)

Total unique ner ingredients strings in this 1000-recipe chunk: 1122

shape: (10, 2)
┌─────────────┬──────────────────────────────────┐
│ recipe_id   ┆ ner_ingredients                  │
│ ---         ┆ ---                              │
│ str         ┆ str                              │
╞═════════════╪══════════════════════════════════╡
│ recipenlg_0 ┆ brown sugar                      │
│ recipenlg_0 ┆ milk                             │
│ recipenlg_0 ┆ vanilla                          │
│ recipenlg_0 ┆ nuts                             │
│ recipenlg_0 ┆ butter                           │
│ recipenlg_0 ┆ bite size shredded rice biscuits │
│ recipenlg_1 ┆ beef                             │
│ recipenlg_1 ┆ chicken breasts                  │
│ recipenlg_1 ┆ cream of mushroom soup           │
│ recipenlg_1 ┆ sour cream                       │
└─────────────┴──────────────────────────────────┘

In [14]:
df = pl.read_parquet("../data/s03_processed/unified_corpus.parquet")

print(f"Total rows: {df.height:,}")
print("\nSchema details:")
print(df.schema)

print("\nSample Recipe:")
print(df.sample(1).to_dicts()[0])

Total rows: 2,231,142

Schema details:
Schema({'recipe_id': String, 'source_dataset': String, 'language': String, 'raw_ingredients': List(String)})

Sample Recipe:
{'recipe_id': 'recipenlg_1193810', 'source_dataset': 'recipenlg', 'language': 'en', 'raw_ingredients': ['shrimp', 'mayonnaise', 'chicken broth', 'lemon rind', 'lemon juice', 'ginger', 'clove garlic', 'sesame oil', 'fresh asparagus', 'hot cooked penne pasta', 'lemon pepper', 'salt']}